### ISSUE TITLE
Requesting  to Add capture dns query as well

### ISSUE THREAD

**Issue by ipinternet** [MusaChowdhury/Fast-Logger#1]
is it possible to capture dns query or visited web url with logs and save it to database?

it is also very helpful if it is done by triggering or configuring on/off function manually

**Comment by MusaChowdhury** [comment]
1. Yes, DNS queries or any other arbitrary data chunk can be captured if the log source provides it. For example, if a MikroTik device (router) provides logs along with DNS queries, you just need to add the proper regular expression to capture this information. This method is the easiest if the log-providing source includes everything that needs to be saved.

2. If the log-providing source (router) doesn't have a way to include certain necessary information, then for that particular use case, the backend engine will need to be modified to generate or capture the missing information.

3. Thanks for bringing this up! If you'd like to add a feature for the IP field, you're welcome to create a pull request in a separate branch. Your contribution would be greatly appreciated!
