### ISSUE TITLE
how to add mikrotik

### ISSUE THREAD

**Issue by hasan2021** [MusaChowdhury/Fast-Logger#2]
![image](https://github.com/user-attachments/assets/a2cdf04d-a729-4372-a17b-f23a1ebe8c41)

**Comment by MusaChowdhury** [comment]
First, you need to follow the instructions given in the error message. 
The engine name must be in lowercase letters. 
The engine port must be between 2000 and 40000, which means you can use any available port within this range. You can adjust the port in your MikroTik log system accordingly.
